"use client"; // This is a client component

import { Inter } from "next/font/google";
import "./globals.css";
import { Web3ReactProvider } from "@web3-react/core";
import { Web3Provider } from "@ethersproject/providers";

const inter = Inter({ subsets: ["latin"] });

const getLibrary = (provider) => {
  return new Web3Provider(provider);
};
/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }) {
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <Component {...pageProps} />
    </Web3ReactProvider>
  );
}

export default MyApp;
*/

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Web3ReactProvider getLibrary={getLibrary}>
        <body className={inter.className}>{children}</body>
      </Web3ReactProvider>
    </html>
  );
}
